### ISSUE TITLE
Set HTML spanned text in notification

### ISSUE THREAD

**Issue by mahbub-java** [isradeleon/Notify-Android#2]
Thanks for nice work. I use it heavily. One thing is **.setContent** Only accept String. But by using **Notification.Builder** can set **.setContectText** pass parameter **CharSequesce** which actually accept **Spanned** as well. So why limitation.

**Comment by isradeleon** [comment]
Allow title & content to be CharSequence in v1.0.5 (3d9b70f8939dbd32c0175e786c56f8250d897229)
