### ISSUE TITLE
Library crashes in API31

### ISSUE THREAD

**Issue by rtsketo** [isradeleon/Notify-Android#3]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent. Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by isradeleon** [comment]
Thank you so much for your contribution! I didn't know that, already merged your changes in v1.0.5 (969dba9b2f10aac2a3a15b2bfcbf9a046f1c1973)
